### ISSUE TITLE
Regression: CTRL-X completion does not work

### ISSUE THREAD

**Issue by e-kwsm** [Shougo/ddc-ui-native#2]
`CTRL-X` completion—`CTRL-X_CTRL-F`, `CTRL-X_CTRL-V`, etc—in insert mode does not work unless it is performed *promptly* after nvim starts. Also, `-- INSERT --` may blink.
This bisects to 5d996271561db01f1a173c5b2481b9b410cf0225.

minimal vimrc:

```vim
set runtimepath-=~/.config/nvim
set runtimepath-=~/.config/nvim/after
set runtimepath-=~/.local/share/nvim/site
set runtimepath-=~/.local/share/nvim/site/after

set runtimepath+=path/to/denops.vim
set runtimepath+=path/to/ddc.vim
set runtimepath+=path/to/ddc-ui-native

call ddc#custom#patch_global('ui', 'native')

call ddc#enable()
```

Steps to reproduce:

1. `nvim -u vimrc`
2. Enter insert mode and press `CTRL-X`; it must show `-- ^X mode (^]^D^E^F^I^K^L^N^O^Ps^U^V^Y)` but doesn’t
3. Successively press `CTRL-F`; it must complete files under the working directory but doesn’t

Environment:

- OS: EndeavourOS
- deno: 1.36.0
- nvim: v0.10.0-dev-766+gef44e5972
- ddc.vim: shougo/ddc.vim@0d49052eb38f92c5f1b8c3bb660dd1fffc1a1e1f
- denops: vim-denops/denops.vim@22e7ae3d712f190b3f46483e6b9dd50a99a9abbd

**Comment by Shougo** [comment]
Fixed.

**Comment by e-kwsm** [comment]
Thank you for your quick response, but it still does not complete a non-empty string.

The following is a gif of `echo 'set runtim' | nvim -u /tmp/vimrc -c 'setf vim' -` under `/`:

![ddc](https://github.com/Shougo/ddc-ui-native/assets/11627708/94f00d3f-4c14-4a6a-bf14-d6f36158f133)

1. it must complete `runtimepath` but it doesn’t; `-- INSERT --` blinks
2. it works as expected only when there are no characters before the cursor; I tried to complete files/directories under `etc` but it doesn’t

**Comment by Shougo** [comment]
Oh.  Too bad.

I have removed `call ddc#hide()`.  Please update.

**Comment by e-kwsm** [comment]
Thanks, now it works.
